name: Discord Bot

on:
  workflow_dispatch:
  push:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Start bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: npm start
